# Generated by Django 2.2.11 on 2020-04-29 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.widgets.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontends', '0002_smsstage_stage'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
                ('code', models.TextField(blank=True, help_text='Javascript used to render model instance', null=True)),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, help_text='Location of package code to import', max_length=256, null=True)),
                ('external', models.BooleanField(default=False, help_text='Used to flag external packages')),
                ('namespace', models.CharField(default='Widget', help_text='This is case insensitive and always capitalized', max_length=24)),
                ('value_parameter', models.CharField(default='event.target.value', help_text='Expected value paramter in associated React synthetic events.', max_length=80)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=ery_backend.widgets.models._gen_default_widget_parameters, help_text='Expected parameters for associated React synthetic events.')),
                ('save_null', models.BooleanField(default=True, help_text='Whether to save null values recieved in a :class:`~ery_backend.modules.widgets.ModuleEvent or:class:`~ery_backend.widgets.models.Event`')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontends.Frontend')),
                ('primary_language', models.ForeignKey(default='en', help_text='Language for the primary implementation of the widget.', on_delete=django.db.models.deletion.SET_DEFAULT, to='languages_plus.Language')),
                ('related_widgets', models.ManyToManyField(blank=True, help_text=':class:`Widget` objects having unique :class:`ery_backend.frontends.models.Frontend` objects to be used as replacements.', to='widgets.Widget')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.eryfile', models.Model),
        ),
        migrations.CreateModel(
            name='WidgetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', help_text='Use to group subset of actions for a given event_type.', max_length=24)),
                ('event_type', models.CharField(choices=[('onBlur', 'On Blur'), ('onChange', 'On Change'), ('onChangeCommitted', 'On Change Committed'), ('onClick', 'On Click'), ('onFocus', 'On Focus'), ('onInput', 'On Input'), ('onKeyDown', 'On Key Down'), ('onMouseUp', 'On Mouse Up'), ('onSubmit', 'On Submit'), ('onScan', 'On Scan'), ('onReply', 'On Reply')], help_text='Javascript or SMS event trigger.', max_length=50)),
                ('widget', models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='widgets.Widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('default_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('from_prop', models.BooleanField(default=False, help_text='Default value should be taken from a passed prop')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='widgets.Widget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('default_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('preview_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='widgets.Widget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetEventStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.TextField(blank=True, help_text='Javascript evaluated on trigger', null=True)),
                ('event_action_type', models.CharField(choices=[('run_code', 'Code'), ('back', 'Back'), ('submit', 'Submit')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('widget_event', models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='widgets.WidgetEvent')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WidgetConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('originator', models.ForeignKey(help_text='Originating :class:`Widget`', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='widgets.Widget')),
                ('target', models.ForeignKey(help_text='Target :class:`Widget`', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='widgets.Widget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
