# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.assets.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, ery_backend.assets.models.GoogleAssetMixin),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
                ('content_type', models.CharField(choices=[('gif', 'image/gif'), ('png', 'image/png'), ('jpeg', 'image/jpeg')], max_length=4)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=('base.eryfile', ery_backend.assets.models.GoogleAssetMixin),
        ),
    ]
