# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        ('stints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='current_stint',
            field=models.ForeignKey(blank=True, help_text='Instance intended for execution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_currentstint', to='stints.Stint'),
        ),
    ]
