# Generated by Django 2.2.11 on 2020-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_lab_current_stint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ('name',)},
        ),
    ]
