# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0002_auto_20200429_2125'),
        ('teams', '0001_initial'),
        ('stints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='stint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stints.Stint'),
        ),
        migrations.AddField(
            model_name='log',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Relevant instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team'),
        ),
    ]
