# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.base.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
                ('mxgraph_xml', models.TextField(blank=True, null=True)),
                ('min_team_size', models.PositiveIntegerField(default=0)),
                ('max_team_size', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.eryfile', models.Model),
        ),
        migrations.CreateModel(
            name='ModuleDefinitionProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDefinitionWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('required_widget', models.BooleanField(default=False, help_text='ModuleDefinitionWidget required to proceed to next :class:`~ery_backend.stages.models.Stage`')),
                ('initial_value', models.CharField(blank=True, help_text='Value displayed in :class:`ModuleDefinitionWidget` immediately on render', max_length=512, null=True)),
                ('random_mode', models.CharField(choices=[('asc', 'Order Ascending'), ('desc', 'Order Descending'), ('shuffle', 'Shuffle (once per display)'), ('random_asc_desc', 'Order random ascending/descending (once per display)')], default='asc', help_text='Randomization option applied during presentation', max_length=50)),
            ],
            options={
                'db_table': 'modules_moduledefinitionwidget',
            },
            bases=(ery_backend.base.mixins.ChoiceHolderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModuleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', help_text='Use to group subset of actions for a given event_type.', max_length=24)),
                ('event_type', models.CharField(choices=[('onBlur', 'On Blur'), ('onChange', 'On Change'), ('onChangeCommitted', 'On Change Committed'), ('onClick', 'On Click'), ('onFocus', 'On Focus'), ('onInput', 'On Input'), ('onKeyDown', 'On Key Down'), ('onMouseUp', 'On Mouse Up'), ('onSubmit', 'On Submit'), ('onScan', 'On Scan'), ('onReply', 'On Reply')], help_text='Javascript or SMS event trigger.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleEventStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_action_type', models.CharField(choices=[('back', 'Back'), ('run_action', 'Run Action'), ('save_var', 'Save Variable'), ('submit', 'Submit')], max_length=14)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WidgetChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=512)),
                ('order', models.IntegerField(default=0, help_text='Default order of presentation')),
            ],
            options={
                'db_table': 'modules_widgetchoice',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WidgetChoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('caption', models.CharField(help_text='Text to be rendered with :class:`WidgetChoice`', max_length=512)),
            ],
            options={
                'db_table': 'modules_widgetchoicetranslation',
            },
        ),
        migrations.CreateModel(
            name='WidgetValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField()),
                ('module_definition_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='modules.ModuleDefinitionWidget')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WidgetValidationTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('error_message', models.CharField(help_text='Error string that will be evaluated with.format(value)', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
                ('widget_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='modules.WidgetValidation')),
            ],
        ),
    ]
