# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('forms', '0002_formfield_validator'),
        ('validators', '0001_initial'),
        ('actions', '0003_auto_20200429_2125'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetvalidation',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='validators.Validator'),
        ),
        migrations.AddField(
            model_name='widgetchoicetranslation',
            name='language',
            field=models.ForeignKey(help_text=':class:`Language` of value content', on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='widgetchoicetranslation',
            name='widget_choice',
            field=models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='modules.WidgetChoice'),
        ),
        migrations.AddField(
            model_name='widgetchoice',
            name='widget',
            field=models.ForeignKey(help_text='Parental model instance', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='modules.ModuleDefinitionWidget'),
        ),
        migrations.AddField(
            model_name='moduleeventstep',
            name='action',
            field=models.ForeignKey(blank=True, help_text='Run upon triggering of specified Javascript event', null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.Action'),
        ),
        migrations.AddField(
            model_name='moduleeventstep',
            name='module_event',
            field=models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='modules.ModuleEvent'),
        ),
        migrations.AddField(
            model_name='moduleevent',
            name='widget',
            field=models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='modules.ModuleDefinitionWidget'),
        ),
        migrations.AddField(
            model_name='moduledefinitionwidget',
            name='form_field',
            field=models.OneToOneField(help_text='If ModuleDefinitionWidget is part of a Form, this is the FormField it belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_definition_widget', to='forms.FormField'),
        ),
        migrations.AddField(
            model_name='moduledefinitionwidget',
            name='module_definition',
            field=models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, related_name='module_widgets', to='modules.ModuleDefinition'),
        ),
    ]
