# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('frontends', '0002_smsstage_stage'),
        ('syncs', '0001_initial'),
        ('stages', '0002_auto_20200429_2125'),
        ('procedures', '0001_initial'),
        ('themes', '0001_initial'),
        ('stints', '0002_auto_20200429_2125'),
        ('widgets', '0001_initial'),
        ('modules', '0003_moduledefinitionwidget_variable_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledefinitionwidget',
            name='widget',
            field=models.ForeignKey(default=9, help_text='Javascript model used to render content of :class:`ModuleDefinitionWidget`', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='module_widgets', to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='moduledefinitionprocedure',
            name='module_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition'),
        ),
        migrations.AddField(
            model_name='moduledefinitionprocedure',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.Procedure'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='default_template',
            field=models.ForeignKey(default=5, help_text='Template used for stage definitions not choosing an explicit template', on_delete=django.db.models.deletion.PROTECT, to='templates.Template'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='default_theme',
            field=models.ForeignKey(default=8, help_text='Theme used for stage definitions not choosing an explicit theme', on_delete=django.db.models.deletion.PROTECT, to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='primary_frontend',
            field=models.ForeignKey(help_text='Language for the primary implementation of the module.', on_delete=django.db.models.deletion.PROTECT, to='frontends.Frontend'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='primary_language',
            field=models.ForeignKey(default='en', help_text='Language for the primary implementation of the module.', on_delete=django.db.models.deletion.SET_DEFAULT, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='start_era',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syncs.Era'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='start_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stints_start_stage', to='stages.StageDefinition'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='warden_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stints_warden_stage', to='stages.StageDefinition'),
        ),
        migrations.AddField(
            model_name='module',
            name='stint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='stints.Stint'),
        ),
        migrations.AddField(
            model_name='module',
            name='stint_definition_module_definition',
            field=models.ForeignKey(help_text='Links to parental instance realized to create current instance in order to track order of presentation.', on_delete=django.db.models.deletion.CASCADE, to='stints.StintDefinitionModuleDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetvalidationtranslations',
            unique_together={('widget_validation', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='widgetchoicetranslation',
            unique_together={('widget_choice', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='widgetchoice',
            unique_together={('widget', 'order'), ('widget', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleevent',
            unique_together={('widget', 'event_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledefinitionwidget',
            unique_together={('name', 'module_definition')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledefinitionprocedure',
            unique_together={('module_definition', 'name')},
        ),
    ]
