# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: babel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='babel.proto',
  package='babel',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x62\x61\x62\x65l.proto\x12\x05\x62\x61\x62\x65l\"/\n\rES6CodeBundle\x12\x1e\n\x06\x62undle\x18\x01 \x03(\x0b\x32\x0e.babel.ES6Code\"/\n\rES5CodeBundle\x12\x1e\n\x06\x62undle\x18\x01 \x03(\x0b\x32\x0e.babel.ES5Code\"%\n\x07\x45S6Code\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"-\n\rErrorLocation\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\"O\n\x07\x45S5Code\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\'\n\terror_loc\x18\x03 \x01(\x0b\x32\x14.babel.ErrorLocation2\xb5\x01\n\x05\x42\x61\x62\x65l\x12\x37\n\rConvertBundle\x12\x14.babel.ES6CodeBundle\x1a\x0e.babel.ES5Code\"\x00\x12\x46\n\x16\x43onvertCodeSplitBundle\x12\x14.babel.ES6CodeBundle\x1a\x14.babel.ES5CodeBundle\"\x00\x12+\n\x07\x43onvert\x12\x0e.babel.ES6Code\x1a\x0e.babel.ES5Code\"\x00\x62\x06proto3')
)




_ES6CODEBUNDLE = _descriptor.Descriptor(
  name='ES6CodeBundle',
  full_name='babel.ES6CodeBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle', full_name='babel.ES6CodeBundle.bundle', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)


_ES5CODEBUNDLE = _descriptor.Descriptor(
  name='ES5CodeBundle',
  full_name='babel.ES5CodeBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle', full_name='babel.ES5CodeBundle.bundle', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=118,
)


_ES6CODE = _descriptor.Descriptor(
  name='ES6Code',
  full_name='babel.ES6Code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='babel.ES6Code.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='babel.ES6Code.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=157,
)


_ERRORLOCATION = _descriptor.Descriptor(
  name='ErrorLocation',
  full_name='babel.ErrorLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='babel.ErrorLocation.line', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column', full_name='babel.ErrorLocation.column', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=204,
)


_ES5CODE = _descriptor.Descriptor(
  name='ES5Code',
  full_name='babel.ES5Code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='babel.ES5Code.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='babel.ES5Code.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_loc', full_name='babel.ES5Code.error_loc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=285,
)

_ES6CODEBUNDLE.fields_by_name['bundle'].message_type = _ES6CODE
_ES5CODEBUNDLE.fields_by_name['bundle'].message_type = _ES5CODE
_ES5CODE.fields_by_name['error_loc'].message_type = _ERRORLOCATION
DESCRIPTOR.message_types_by_name['ES6CodeBundle'] = _ES6CODEBUNDLE
DESCRIPTOR.message_types_by_name['ES5CodeBundle'] = _ES5CODEBUNDLE
DESCRIPTOR.message_types_by_name['ES6Code'] = _ES6CODE
DESCRIPTOR.message_types_by_name['ErrorLocation'] = _ERRORLOCATION
DESCRIPTOR.message_types_by_name['ES5Code'] = _ES5CODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ES6CodeBundle = _reflection.GeneratedProtocolMessageType('ES6CodeBundle', (_message.Message,), {
  'DESCRIPTOR' : _ES6CODEBUNDLE,
  '__module__' : 'babel_pb2'
  # @@protoc_insertion_point(class_scope:babel.ES6CodeBundle)
  })
_sym_db.RegisterMessage(ES6CodeBundle)

ES5CodeBundle = _reflection.GeneratedProtocolMessageType('ES5CodeBundle', (_message.Message,), {
  'DESCRIPTOR' : _ES5CODEBUNDLE,
  '__module__' : 'babel_pb2'
  # @@protoc_insertion_point(class_scope:babel.ES5CodeBundle)
  })
_sym_db.RegisterMessage(ES5CodeBundle)

ES6Code = _reflection.GeneratedProtocolMessageType('ES6Code', (_message.Message,), {
  'DESCRIPTOR' : _ES6CODE,
  '__module__' : 'babel_pb2'
  # @@protoc_insertion_point(class_scope:babel.ES6Code)
  })
_sym_db.RegisterMessage(ES6Code)

ErrorLocation = _reflection.GeneratedProtocolMessageType('ErrorLocation', (_message.Message,), {
  'DESCRIPTOR' : _ERRORLOCATION,
  '__module__' : 'babel_pb2'
  # @@protoc_insertion_point(class_scope:babel.ErrorLocation)
  })
_sym_db.RegisterMessage(ErrorLocation)

ES5Code = _reflection.GeneratedProtocolMessageType('ES5Code', (_message.Message,), {
  'DESCRIPTOR' : _ES5CODE,
  '__module__' : 'babel_pb2'
  # @@protoc_insertion_point(class_scope:babel.ES5Code)
  })
_sym_db.RegisterMessage(ES5Code)



_BABEL = _descriptor.ServiceDescriptor(
  name='Babel',
  full_name='babel.Babel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertBundle',
    full_name='babel.Babel.ConvertBundle',
    index=0,
    containing_service=None,
    input_type=_ES6CODEBUNDLE,
    output_type=_ES5CODE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConvertCodeSplitBundle',
    full_name='babel.Babel.ConvertCodeSplitBundle',
    index=1,
    containing_service=None,
    input_type=_ES6CODEBUNDLE,
    output_type=_ES5CODEBUNDLE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Convert',
    full_name='babel.Babel.Convert',
    index=2,
    containing_service=None,
    input_type=_ES6CODE,
    output_type=_ES5CODE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BABEL)

DESCRIPTOR.services_by_name['Babel'] = _BABEL

# @@protoc_insertion_point(module_scope)
