# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ery_backend.scripts.grpc.engine_pb2 as engine__pb2


class JavascriptEngineStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/main.JavascriptEngine/Run',
        request_serializer=engine__pb2.JavascriptOp.SerializeToString,
        response_deserializer=engine__pb2.Result.FromString,
        )


class JavascriptEngineServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JavascriptEngineServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=engine__pb2.JavascriptOp.FromString,
          response_serializer=engine__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.JavascriptEngine', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
