# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ery_backend.scripts.grpc.ledger_pb2 as ledger__pb2


class LedgerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddAccount = channel.unary_unary(
        '/Ledger/AddAccount',
        request_serializer=ledger__pb2.OwnedAccount.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Buy = channel.unary_unary(
        '/Ledger/Buy',
        request_serializer=ledger__pb2.Purchase.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Deposit = channel.unary_unary(
        '/Ledger/Deposit',
        request_serializer=ledger__pb2.Deposal.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Donate = channel.unary_unary(
        '/Ledger/Donate',
        request_serializer=ledger__pb2.Transferal.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Pay = channel.unary_unary(
        '/Ledger/Pay',
        request_serializer=ledger__pb2.Payment.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Quote = channel.unary_unary(
        '/Ledger/Quote',
        request_serializer=ledger__pb2.Withdrawal.SerializeToString,
        response_deserializer=ledger__pb2.QuoteError.FromString,
        )
    self.Transfer = channel.unary_unary(
        '/Ledger/Transfer',
        request_serializer=ledger__pb2.Transferal.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.ValidateAccount = channel.unary_unary(
        '/Ledger/ValidateAccount',
        request_serializer=ledger__pb2.Account.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )
    self.Withdraw = channel.unary_unary(
        '/Ledger/Withdraw',
        request_serializer=ledger__pb2.Withdrawal.SerializeToString,
        response_deserializer=ledger__pb2.StatusError.FromString,
        )


class LedgerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Buy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deposit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Donate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Quote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Withdraw(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LedgerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddAccount': grpc.unary_unary_rpc_method_handler(
          servicer.AddAccount,
          request_deserializer=ledger__pb2.OwnedAccount.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Buy': grpc.unary_unary_rpc_method_handler(
          servicer.Buy,
          request_deserializer=ledger__pb2.Purchase.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Deposit': grpc.unary_unary_rpc_method_handler(
          servicer.Deposit,
          request_deserializer=ledger__pb2.Deposal.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Donate': grpc.unary_unary_rpc_method_handler(
          servicer.Donate,
          request_deserializer=ledger__pb2.Transferal.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Pay': grpc.unary_unary_rpc_method_handler(
          servicer.Pay,
          request_deserializer=ledger__pb2.Payment.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Quote': grpc.unary_unary_rpc_method_handler(
          servicer.Quote,
          request_deserializer=ledger__pb2.Withdrawal.FromString,
          response_serializer=ledger__pb2.QuoteError.SerializeToString,
      ),
      'Transfer': grpc.unary_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=ledger__pb2.Transferal.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'ValidateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateAccount,
          request_deserializer=ledger__pb2.Account.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
      'Withdraw': grpc.unary_unary_rpc_method_handler(
          servicer.Withdraw,
          request_deserializer=ledger__pb2.Withdrawal.FromString,
          response_serializer=ledger__pb2.StatusError.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Ledger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
