FROM python:3.6.10-alpine3.11

ENV PYTHONUNBUFFERED 1

# Set up user and groups
RUN addgroup -S ery_backend \
    && adduser -S ery_backend ery_backend

# Setup run script
COPY ./config/docker/scripts/entrypoint-non-production.sh /
RUN sed -i 's/\r//' /entrypoint-non-production.sh \
    && chmod +x /entrypoint-non-production.sh \
    && chown ery_backend /entrypoint-non-production.sh

COPY ./config/docker/scripts/start-test.sh /start-test.sh
RUN chmod +x /start-test.sh

RUN mkdir -p /home/ery_backend
RUN chown -R ery_backend /home/ery_backend

RUN apk update && apk upgrade && apk add --virtual build-deps --update --no-cache \
        g++ \
        gcc \
        python3-dev \
        musl-dev \
        libffi-dev \
        libffi \
        jpeg-dev \
        zlib-dev \
        postgresql-dev \
        libxml2-dev \
        libxslt-dev
	
RUN pip install --upgrade pip
RUN pip install setuptools
RUN pip install numpy
# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/backend/test.txt && rm -rf /requirements

# Clean up build tools
RUN apk del build-deps

# Install libraries
RUN apk update && apk upgrade && apk add --update --no-cache \
    bash \
    make \
    libxslt \
    libxml2 \
    libstdc++ \
    postgresql-libs

COPY . /ery_backend

RUN chown -R ery_backend /ery_backend

USER ery_backend
WORKDIR /ery_backend

ENTRYPOINT ["/entrypoint-non-production.sh"]
