# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('stages', '0001_initial'),
        ('hands', '0003_auto_20200429_2125'),
        ('themes', '0001_initial'),
        ('conditions', '0001_initial'),
        ('actions', '0003_auto_20200429_2125'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='templates.Template'),
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_templates', to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='stagedefinition',
            name='module_definition',
            field=models.ForeignKey(help_text='The module definition this StageDefinition belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stage_definitions', to='modules.ModuleDefinition'),
        ),
        migrations.AddField(
            model_name='stagedefinition',
            name='pre_action',
            field=models.ForeignKey(blank=True, help_text=':class:`~ery_backend.actions.models.Action` run before rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Action'),
        ),
        migrations.AddField(
            model_name='stagedefinition',
            name='templates',
            field=models.ManyToManyField(help_text='Connected :class:`~ery_backend.templates.models.Template` instances', through='stages.StageTemplate', to='templates.Template'),
        ),
        migrations.AddField(
            model_name='stagebreadcrumb',
            name='hand',
            field=models.ForeignKey(help_text='Player (:class:`~ery_backend.users.models.User` or :class:`~ery_backend.robots.models.Robot`) tracked through a :class:`~ery_backend.stints.models.Stint`', on_delete=django.db.models.deletion.CASCADE, to='hands.Hand'),
        ),
        migrations.AddField(
            model_name='stagebreadcrumb',
            name='next_breadcrumb',
            field=models.ForeignKey(blank=True, help_text='Records next instance in chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_crumb', to='stages.StageBreadcrumb'),
        ),
        migrations.AddField(
            model_name='stagebreadcrumb',
            name='previous_breadcrumb',
            field=models.ForeignKey(blank=True, help_text='Records last instance in chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_crumb', to='stages.StageBreadcrumb'),
        ),
        migrations.AddField(
            model_name='stagebreadcrumb',
            name='stage',
            field=models.ForeignKey(help_text='Current location of :class:`~ery_backend.hands.models.Hand`', on_delete=django.db.models.deletion.CASCADE, to='stages.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_definition',
            field=models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, to='stages.StageDefinition'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='condition',
            field=models.ForeignKey(blank=True, help_text='Condition of execution', null=True, on_delete=django.db.models.deletion.CASCADE, to='conditions.Condition'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='next_stage_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirectTargets', to='stages.StageDefinition'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='stage_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='stages.StageDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='stagetemplateblocktranslation',
            unique_together={('stage_template_block', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='stagetemplateblock',
            unique_together={('stage_template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stagedefinition',
            unique_together={('name', 'module_definition')},
        ),
    ]
