# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0002_auto_20200429_2125'),
        ('stints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestar',
            name='stint_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stints.StintDefinition'),
        ),
    ]
