# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('comments', '0006_filestar_validator'),
        ('assets', '0001_initial'),
        ('procedures', '0001_initial'),
        ('themes', '0001_initial'),
        ('validators', '0001_initial'),
        ('datasets', '0001_initial'),
        ('stints', '0002_auto_20200429_2125'),
        ('widgets', '0001_initial'),
        ('modules', '0003_moduledefinitionwidget_variable_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filestar',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text=':class:`~ery_backend.users.models.User` uploaded :class:`~ery_backend.datasets.models.Dataset`', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text=':class:`~ery_backend.users.models.User` uploaded image.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.ImageAsset'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='module_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Procedure'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='stint_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stints.StintDefinition'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.Template'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validators.Validator'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
    ]
