# Generated by Django 2.2.11 on 2020-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stint_specifications', '0002_auto_20200429_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stintspecification',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='stintspecificationallowedlanguagefrontend',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='stintspecificationrobot',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='stintspecificationvariable',
            options={'ordering': ('created',)},
        ),
    ]
