apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ery-sms-runner
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ery-sms-runner
    spec:
      containers:
      - name: ery-sms-runner
        args:
          - ./sms_runner.py
        image: gcr.io/eryservices-176219/ery_sms_runner
        env:
        - name: DEPLOYMENT
          value: staging
        - name: REDIS_URL
          value: 'redis://10.0.0.11:6379'
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: secret_key
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ery-cloudsql-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ery-cloudsql-secret
              key: password
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.sms_runner.production"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        volumeMounts:
        - name: ery-sms-runner-credentials
          mountPath: /var/secrets/google
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.12
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=eryservices-176219:us-east4:ery-staging=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: ery-sql-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      restartPolicy: Always
      volumes:
      - name: ery-sms-runner-credentials
        secret:
          secretName: ery-sms-runner-credentials
      - name: ery-sql-credentials
        secret:
          secretName: ery-sql-credentials
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
