# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
                ('code', models.TextField(blank=True, null=True)),
                ('regex', models.TextField(blank=True, null=True)),
                ('nullable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=('base.eryfile',),
        ),
        migrations.CreateModel(
            name='ValidatorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('error_message', models.CharField(blank=True, help_text='Error string that will be evaluated with.format(value)', max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='validators.Validator')),
            ],
            options={
                'unique_together': {('validator', 'language')},
            },
        ),
    ]
