# Generated by Django 2.2.11 on 2020-04-29 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.base.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=621, unique=True)),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('button_text', models.CharField(max_length=24)),
                ('submit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormButtonList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=621, unique=True)),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('initial_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('helper_text', models.TextField()),
                ('random_mode', models.CharField(choices=[('asc', 'Order Ascending'), ('desc', 'Order Descending'), ('shuffle', 'Shuffle (once per display)'), ('random_asc_desc', 'Order random ascending/descending (once per display)')], default='asc', help_text='Randomization option applied during presentation', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('disable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conditions.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=(ery_backend.base.mixins.ChoiceHolderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=512)),
                ('order', models.IntegerField(default=0, help_text='Default order of presentation')),
                ('field', models.ForeignKey(help_text='Parental model instance', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forms.FormField')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField()),
                ('tab_order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms.Form')),
            ],
            options={
                'ordering': ('order', 'tab_order'),
            },
        ),
        migrations.CreateModel(
            name='FormFieldChoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('caption', models.CharField(help_text='Text to be rendered with :class:`WidgetChoice`', max_length=512)),
                ('field_choice', models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forms.FormFieldChoice')),
                ('language', models.ForeignKey(help_text=':class:`Language` of value content', on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
            ],
        ),
        migrations.AddField(
            model_name='formfield',
            name='form_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='forms.FormItem'),
        ),
    ]
