# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
        ('forms', '0002_formfield_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='variable_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='variables.VariableDefinition'),
        ),
    ]
