# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0001_initial'),
        ('modules', '0003_moduledefinitionwidget_variable_definition'),
        ('conditions', '0002_auto_20200429_2125'),
        ('forms', '0003_formfield_variable_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='formbuttonlist',
            name='form_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_list', to='forms.FormItem'),
        ),
        migrations.AddField(
            model_name='formbutton',
            name='button_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='forms.FormButtonList'),
        ),
        migrations.AddField(
            model_name='formbutton',
            name='disable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conditions.Condition'),
        ),
        migrations.AddField(
            model_name='formbutton',
            name='hide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='++', to='conditions.Condition'),
        ),
        migrations.AddField(
            model_name='formbutton',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='form',
            name='module_definition',
            field=models.ForeignKey(help_text='The module definition this Form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='modules.ModuleDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='formitem',
            unique_together={('form', 'tab_order')},
        ),
        migrations.AlterUniqueTogether(
            name='formfieldchoicetranslation',
            unique_together={('field_choice', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='formfieldchoice',
            unique_together={('field', 'order'), ('field', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='formbutton',
            unique_together={('name', 'button_list')},
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('name', 'module_definition')},
        ),
    ]
