# Generated by Django 2.2.11 on 2020-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200429_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbutton',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='formbuttonlist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='formfieldchoicetranslation',
            options={'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set(),
        ),
    ]
