# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
                ('legal_text', models.TextField(blank=True, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ImageAsset')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=('base.eryfile',),
        ),
        migrations.CreateModel(
            name='ThemeTypography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(choices=[('h1', 'Header 1'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4'), ('h5', 'Header 5'), ('h6', 'Header 6'), ('subtitle1', 'Subtitle 1'), ('subtitle2', 'Subtitle 2'), ('body1', 'Body 1'), ('body2', 'Body 2'), ('button', 'Button'), ('caption', 'Caption'), ('overline', 'Overline')], help_text='Material UI typography variant type.', max_length=12)),
                ('font_size', models.CharField(help_text='Exact (in pixels) or responsive (in rem) specification of font size for given typography.', max_length=15)),
                ('font_weight', models.CharField(choices=[('normal', 'Equivalent of 400.'), ('bold', 'Equivalent of 700.'), ('bolder', 'Bolder than the inherited font weight.'), ('lighter', 'Lighter than the inherited font weight.'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('initial', 'Initial value provided by browser.'), ('inherit', 'Value provider by parent (if any). If none, uses browser default.')], help_text='Exact (numerical) or descriptive (e.g., bold) specificationof font emphasis for given typography.', max_length=12)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=12)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typographies', to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='ThemePalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('error', 'Error')], help_text='Material UI color intention type.', max_length=12)),
                ('main', models.CharField(help_text='Default color tone.', max_length=7)),
                ('light', models.CharField(blank=True, help_text='Lighter tonal offset of main color.', max_length=7, null=True)),
                ('dark', models.CharField(blank=True, help_text='Darker tonal offset of main color.', max_length=7, null=True)),
                ('contrast_text', models.CharField(blank=True, help_text='Contrast between background and text.', max_length=7, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='themes.Theme')),
            ],
        ),
    ]
