# Generated by Django 2.2.11 on 2020-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='themepalette',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='themetypography',
            options={'ordering': ('created',)},
        ),
    ]
