# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontends', '0002_smsstage_stage'),
        ('widgets', '0001_initial'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewidget',
            name='widget',
            field=models.ForeignKey(help_text='Javascript model used to render content of :class:`TemplateWidget`', on_delete=django.db.models.deletion.PROTECT, related_name='template_widgets', to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='templateblocktranslation',
            name='frontend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontends.Frontend'),
        ),
        migrations.AddField(
            model_name='templateblocktranslation',
            name='language',
            field=models.ForeignKey(help_text=':class:`Language` used for rendering content', on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='templateblocktranslation',
            name='template_block',
            field=models.ForeignKey(help_text='Parental :class:`TemplateBlock`', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='templates.TemplateBlock'),
        ),
        migrations.AddField(
            model_name='templateblock',
            name='template',
            field=models.ForeignKey(help_text='Parental :class:`Template` instance', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='templates.Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='frontend',
            field=models.ForeignKey(blank=True, help_text=':class:`Frontend` instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontends.Frontend'),
        ),
        migrations.AddField(
            model_name='template',
            name='parental_template',
            field=models.ForeignKey(blank=True, help_text='Parental :class:`Template` instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='templates.Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='primary_language',
            field=models.ForeignKey(default='en', help_text=':class:`Language` instance used as default for all related content', on_delete=django.db.models.deletion.SET_DEFAULT, to='languages_plus.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='templatewidget',
            unique_together={('template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='templateblocktranslation',
            unique_together={('template_block', 'language', 'frontend')},
        ),
        migrations.AlterUniqueTogether(
            name='templateblock',
            unique_together={('template', 'name')},
        ),
    ]
