# Generated by Django 2.2.11 on 2020-04-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('templates', '0003_auto_20200430_0148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateblocktranslation',
            unique_together={('template_block', 'language')},
        ),
        migrations.RemoveField(
            model_name='templateblocktranslation',
            name='frontend',
        ),
    ]
