# Generated by Django 2.2.11 on 2020-04-29 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.base.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncs', '0001_initial'),
        ('stints', '0001_initial'),
        ('hands', '0002_auto_20200429_2125'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of model instance', max_length=256)),
                ('era', models.ForeignKey(blank=True, help_text='Used to synchronize current :class:`Team` instances with other instances', null=True, on_delete=django.db.models.deletion.CASCADE, to='syncs.Era')),
            ],
            options={
                'abstract': False,
            },
            bases=(ery_backend.base.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamNetworkDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('static_network', models.TextField(blank=True, null=True)),
                ('generation_method', models.CharField(blank=True, choices=[('connected_newman_watts_strogatz_graph', 'Connected Newman-Watts-Strogatz'), ('neighborhood_graph', 'Random with neighborhoods of size')], max_length=100, null=True)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('module_definition', models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition')),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'module_definition')},
            },
        ),
        migrations.CreateModel(
            name='TeamNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('network', models.TextField()),
                ('stint', models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, to='stints.Stint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hands.Hand')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='team',
            name='hands',
            field=models.ManyToManyField(help_text='Grouped children', related_name='teams', through='teams.TeamHand', to='hands.Hand'),
        ),
        migrations.AddField(
            model_name='team',
            name='stint',
            field=models.ForeignKey(blank=True, help_text='Parental instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='stints.Stint'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_network_definition',
            field=models.ForeignKey(blank=True, help_text='Social network used to render instance during :class:`~ery_backend.stints.models.Stint`', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.TeamNetworkDefinition'),
        ),
    ]
