# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.IntegerField(default=0)),
                ('invert_condition', models.BooleanField(default=False)),
                ('for_each', models.CharField(choices=[('current_hand_only', 'Current Hand Only'), ('hand_in_neighborhood', 'Hand in Neighborhood'), ('hand_in_team', 'Hand in Team'), ('hand_in_stint', 'Hand in Stint'), ('team_in_stint', 'Team in Stint')], default='current_hand_only', max_length=50)),
                ('action_type', models.CharField(choices=[('set_variable', 'Set Variable'), ('set_era', 'Set Era'), ('run_code', 'Run Code'), ('log', 'Log'), ('save_data', 'Save Data'), ('subaction', 'Subaction'), ('pay_users', 'Pay Users'), ('quit', 'Quit')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=4096, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('log_message', models.CharField(blank=True, max_length=512, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='actions.Action')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
