# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
        ('actions', '0003_auto_20200429_2125'),
        ('modules', '0002_auto_20200429_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstep',
            name='to_save',
            field=models.ManyToManyField(blank=True, related_name='saved_via', to='variables.VariableDefinition'),
        ),
        migrations.AddField(
            model_name='actionstep',
            name='variable_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_action_steps', to='variables.VariableDefinition'),
        ),
        migrations.AddField(
            model_name='action',
            name='module_definition',
            field=models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'module_definition')},
        ),
    ]
