# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('commands', '0001_initial'),
        ('frontends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtemplateblocktranslation',
            name='frontend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='command_template_block_translations', to='frontends.Frontend'),
        ),
        migrations.AddField(
            model_name='commandtemplateblocktranslation',
            name='language',
            field=models.ForeignKey(help_text='Used to render content', on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='commandtemplateblock',
            name='command_template',
            field=models.ForeignKey(help_text='Parental instance', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='commands.CommandTemplate'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='command',
            field=models.ForeignKey(help_text='Parental instance.', on_delete=django.db.models.deletion.CASCADE, related_name='command_templates', to='commands.Command'),
        ),
    ]
