# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('actions', '0003_auto_20200429_2125'),
        ('commands', '0002_auto_20200429_2125'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtemplate',
            name='template',
            field=models.ForeignKey(help_text='Parental instance for child :class:`CommandTemplateBlock` instances', on_delete=django.db.models.deletion.CASCADE, related_name='command_templates', to='templates.Template'),
        ),
        migrations.AddField(
            model_name='command',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggering_commands', to='actions.Action'),
        ),
        migrations.AddField(
            model_name='command',
            name='module_definition',
            field=models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='commandtemplateblocktranslation',
            unique_together={('command_template_block', 'language', 'frontend')},
        ),
        migrations.AlterUniqueTogether(
            name='commandtemplateblock',
            unique_together={('command_template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('name', 'module_definition')},
        ),
    ]
