# Generated by Django 2.2.11 on 2020-04-29 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ery_backend.base.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('panicked', 'Panicked')], help_text='Indicates the state of the current :class:`Stint`', max_length=24, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('layout', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ery_backend.base.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StintDefinition',
            fields=[
                ('eryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.EryFile')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=('base.eryfile',),
        ),
        migrations.CreateModel(
            name='StintDefinitionModuleDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='StintDefinitionVariableDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stint_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stint_definition_variable_definitions', to='stints.StintDefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
