# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.utils.timezone
import ery_backend.base.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('current_payoff', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Used for inactivity timeouts', null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('timedout', 'Timed Out'), ('quit', 'Quit'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], help_text='Indicates current state of :class:`Hand`', max_length=24, null=True)),
            ],
            bases=(ery_backend.base.mixins.LogMixin, models.Model),
        ),
    ]
