# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hands', '0001_initial'),
        ('stages', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='current_breadcrumb',
            field=models.OneToOneField(blank=True, help_text='Last traversed instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hand', to='stages.StageBreadcrumb'),
        ),
        migrations.AddField(
            model_name='hand',
            name='current_module',
            field=models.ForeignKey(blank=True, help_text='Used in multi :class:`~ery_backend.modules.models.Module` :class:`~ery_backend.stints.models.Stint` to proceed from one :class:~ery_backend.modules.models.Module` to the next.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hands', to='modules.Module'),
        ),
    ]
