# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('robots', '0001_initial'),
        ('frontends', '0002_smsstage_stage'),
        ('syncs', '0001_initial'),
        ('hands', '0002_auto_20200429_2125'),
        ('stages', '0001_initial'),
        ('teams', '0001_initial'),
        ('stints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='current_team',
            field=models.ForeignKey(blank=True, help_text='Current grouping (with other :class:`Hand` instances) in :class:`~ery_backend.stints.models.Stint`', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hands', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='hand',
            name='era',
            field=models.ForeignKey(blank=True, help_text='Used to synchronize progression through :class:`~ery_backend.stints.models.Stint` with other :class:`Hand` instances', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='syncs.Era'),
        ),
        migrations.AddField(
            model_name='hand',
            name='frontend',
            field=models.ForeignKey(default=3, help_text='Current client frontend', on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='frontends.Frontend'),
        ),
        migrations.AddField(
            model_name='hand',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='hand',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot_hands', to='robots.Robot'),
        ),
        migrations.AddField(
            model_name='hand',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Current position in :class:`~ery_backend.stints.models.Stint`', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='stages.Stage'),
        ),
        migrations.AddField(
            model_name='hand',
            name='stint',
            field=models.ForeignKey(blank=True, help_text='Parental instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='stints.Stint'),
        ),
    ]
