# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
        ('modules', '0002_auto_20200429_2125'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='left_variable_definition',
            field=models.ForeignKey(blank=True, help_text=':class:`~ery_backend.variables.models.VariableDefinition` for left side of :class:`Condition` from which to obtain value based on  :class:`~ery_backend.hands.models.Hand` during :py:meth:`Condition.evaluate`', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='variables.VariableDefinition'),
        ),
        migrations.AddField(
            model_name='condition',
            name='module_definition',
            field=models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition'),
        ),
        migrations.AddField(
            model_name='condition',
            name='right_sub_condition',
            field=models.ForeignKey(blank=True, help_text=':class:`Condition` for right side of current instance from which to obtain value (via :py:meth:`Condition.evaluate`) based on :class:`~ery_backend.hands.models.Hand` or :class:`~ery_backend.teams.models.Team`', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conditions.Condition'),
        ),
        migrations.AddField(
            model_name='condition',
            name='right_variable_definition',
            field=models.ForeignKey(blank=True, help_text=':class:`~ery_backend.variables.models.VariableDefinition` for left side of :class:`Condition` from which to obtain value based on  :class:`~ery_backend.hands.models.Hand` during :py:meth:`Condition.evaluate`', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='variables.VariableDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('name', 'module_definition')},
        ),
    ]
