# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0002_actionstep_condition'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=621, unique=True)),
                ('name', models.CharField(help_text='Name of the model instance.', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='Comment documenting the purpose of this model instance.', null=True)),
                ('is_team', models.BooleanField(default=False)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggering_eras', to='actions.Action')),
                ('module_definition', models.ForeignKey(help_text='Parent :class:`~ery_backend.modules.models.ModuleDefinition`', on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition')),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'module_definition')},
            },
        ),
    ]
