# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('assets', '0001_initial'),
        ('procedures', '0001_initial'),
        ('modules', '0001_initial'),
        ('themes', '0001_initial'),
        ('datasets', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('stints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether user should supercede permission system')),
                ('is_creator', models.BooleanField(default=False, help_text='Designates whether user should be allowed to create stints')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Profile information as provided by Facebook, Google, Linkedin or edited by user')),
                ('experience', django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='Experience information as provided by Facebook, Google, Linkedin or edited by user')),
                ('privacy', models.CharField(choices=[('global', 'Global'), ('open', 'Open'), ('closed', 'Closed')], default='global', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_type', models.CharField(choices=[('dataset', 'Dataset'), ('image_asset', 'Image Asset'), ('procedure', 'Procedure'), ('module_definition', 'Module Definition'), ('stint_definition', 'Stint Definition'), ('template', 'Template'), ('widget', 'Widget'), ('theme', 'Theme'), ('validator', 'Validator')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, help_text=':class:`~ery_backend.users.models.User` uploaded :class:`~ery_backend.datasets.models.Dataset`', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
                ('image_asset', models.ForeignKey(blank=True, help_text=':class:`~ery_backend.users.models.User` uploaded image.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.ImageAsset')),
                ('module_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.ModuleDefinition')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Procedure')),
                ('stint_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stints.StintDefinition')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.Template')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
