# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0006_link_widget'),
        ('widgets', '0001_initial'),
        ('assets', '0001_initial'),
        ('users', '0002_filetouch_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetouch',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(help_text='The users who are following this user.', through='users.UserRelation', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all privileges granted to each role of their groups.', related_name='user_set', related_query_name='user', to='users.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.Folder'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ImageAsset'),
        ),
    ]
