# Generated by Django 2.2.11 on 2020-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        ('frontends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsstage',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stages.Stage'),
        ),
    ]
