# Generated by Django 2.2.11 on 2020-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontends', '0002_smsstage_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontend',
            options={'ordering': ('name',)},
        ),
    ]
